// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Persona struct {
	ID        int64  `json:"id"`
	Nombre    string `json:"nombre"`
	Ocupacion string `json:"ocupacion"`
	Edad      int32  `json:"edad"`
}
