// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: persona.sql

package database

import (
	"context"
)

const createPersona = `-- name: CreatePersona :one
INSERT INTO "persona"(
    nombre,
    ocupacion
)values ($1,$2) returning id, nombre, ocupacion
`

type CreatePersonaParams struct {
	Nombre    string `json:"nombre"`
	Ocupacion string `json:"ocupacion"`
}

func (q *Queries) CreatePersona(ctx context.Context, arg CreatePersonaParams) (Persona, error) {
	row := q.db.QueryRowContext(ctx, createPersona, arg.Nombre, arg.Ocupacion)
	var i Persona
	err := row.Scan(&i.ID, &i.Nombre, &i.Ocupacion)
	return i, err
}
