// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"
)

type Querier interface {
	CreatePersona(ctx context.Context, arg CreatePersonaParams) (Persona, error)
}

var _ Querier = (*Queries)(nil)
