// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: ocupacion.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ocupacion_Trabajos int32

const (
	Ocupacion_Desconocido Ocupacion_Trabajos = 0
	Ocupacion_Progrmador  Ocupacion_Trabajos = 1
	Ocupacion_Disenador   Ocupacion_Trabajos = 2
	Ocupacion_Pintor      Ocupacion_Trabajos = 3
)

// Enum value maps for Ocupacion_Trabajos.
var (
	Ocupacion_Trabajos_name = map[int32]string{
		0: "Desconocido",
		1: "Progrmador",
		2: "Disenador",
		3: "Pintor",
	}
	Ocupacion_Trabajos_value = map[string]int32{
		"Desconocido": 0,
		"Progrmador":  1,
		"Disenador":   2,
		"Pintor":      3,
	}
)

func (x Ocupacion_Trabajos) Enum() *Ocupacion_Trabajos {
	p := new(Ocupacion_Trabajos)
	*p = x
	return p
}

func (x Ocupacion_Trabajos) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ocupacion_Trabajos) Descriptor() protoreflect.EnumDescriptor {
	return file_ocupacion_proto_enumTypes[0].Descriptor()
}

func (Ocupacion_Trabajos) Type() protoreflect.EnumType {
	return &file_ocupacion_proto_enumTypes[0]
}

func (x Ocupacion_Trabajos) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ocupacion_Trabajos.Descriptor instead.
func (Ocupacion_Trabajos) EnumDescriptor() ([]byte, []int) {
	return file_ocupacion_proto_rawDescGZIP(), []int{0, 0}
}

type Ocupacion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ocupacion Ocupacion_Trabajos `protobuf:"varint,1,opt,name=Ocupacion,proto3,enum=proto.Ocupacion_Trabajos" json:"Ocupacion,omitempty"`
}

func (x *Ocupacion) Reset() {
	*x = Ocupacion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ocupacion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ocupacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ocupacion) ProtoMessage() {}

func (x *Ocupacion) ProtoReflect() protoreflect.Message {
	mi := &file_ocupacion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ocupacion.ProtoReflect.Descriptor instead.
func (*Ocupacion) Descriptor() ([]byte, []int) {
	return file_ocupacion_proto_rawDescGZIP(), []int{0}
}

func (x *Ocupacion) GetOcupacion() Ocupacion_Trabajos {
	if x != nil {
		return x.Ocupacion
	}
	return Ocupacion_Desconocido
}

var File_ocupacion_proto protoreflect.FileDescriptor

var file_ocupacion_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x63, 0x75, 0x70, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x09, 0x4f, 0x63, 0x75,
	0x70, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x09, 0x4f, 0x63, 0x75, 0x70, 0x61, 0x63,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4f, 0x63, 0x75, 0x70, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x62,
	0x61, 0x6a, 0x6f, 0x73, 0x52, 0x09, 0x4f, 0x63, 0x75, 0x70, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x22,
	0x46, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x62, 0x61, 0x6a, 0x6f, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x6f, 0x6e, 0x6f, 0x63, 0x69, 0x64, 0x6f, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x6d, 0x61, 0x64, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x44, 0x69, 0x73, 0x65, 0x6e, 0x61, 0x64, 0x6f, 0x72, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x50,
	0x69, 0x6e, 0x74, 0x6f, 0x72, 0x10, 0x03, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ocupacion_proto_rawDescOnce sync.Once
	file_ocupacion_proto_rawDescData = file_ocupacion_proto_rawDesc
)

func file_ocupacion_proto_rawDescGZIP() []byte {
	file_ocupacion_proto_rawDescOnce.Do(func() {
		file_ocupacion_proto_rawDescData = protoimpl.X.CompressGZIP(file_ocupacion_proto_rawDescData)
	})
	return file_ocupacion_proto_rawDescData
}

var file_ocupacion_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ocupacion_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ocupacion_proto_goTypes = []interface{}{
	(Ocupacion_Trabajos)(0), // 0: proto.Ocupacion.Trabajos
	(*Ocupacion)(nil),       // 1: proto.Ocupacion
}
var file_ocupacion_proto_depIdxs = []int32{
	0, // 0: proto.Ocupacion.Ocupacion:type_name -> proto.Ocupacion.Trabajos
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ocupacion_proto_init() }
func file_ocupacion_proto_init() {
	if File_ocupacion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ocupacion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ocupacion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ocupacion_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocupacion_proto_goTypes,
		DependencyIndexes: file_ocupacion_proto_depIdxs,
		EnumInfos:         file_ocupacion_proto_enumTypes,
		MessageInfos:      file_ocupacion_proto_msgTypes,
	}.Build()
	File_ocupacion_proto = out.File
	file_ocupacion_proto_rawDesc = nil
	file_ocupacion_proto_goTypes = nil
	file_ocupacion_proto_depIdxs = nil
}
