// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ServerRpc_CreatePerson_FullMethodName = "/proto.ServerRpc/CreatePerson"
)

// ServerRpcClient is the client API for ServerRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerRpcClient interface {
	CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error)
}

type serverRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewServerRpcClient(cc grpc.ClientConnInterface) ServerRpcClient {
	return &serverRpcClient{cc}
}

func (c *serverRpcClient) CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*CreatePersonResponse, error) {
	out := new(CreatePersonResponse)
	err := c.cc.Invoke(ctx, ServerRpc_CreatePerson_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerRpcServer is the server API for ServerRpc service.
// All implementations must embed UnimplementedServerRpcServer
// for forward compatibility
type ServerRpcServer interface {
	CreatePerson(context.Context, *CreatePersonRequest) (*CreatePersonResponse, error)
	mustEmbedUnimplementedServerRpcServer()
}

// UnimplementedServerRpcServer must be embedded to have forward compatible implementations.
type UnimplementedServerRpcServer struct {
}

func (UnimplementedServerRpcServer) CreatePerson(context.Context, *CreatePersonRequest) (*CreatePersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePerson not implemented")
}
func (UnimplementedServerRpcServer) mustEmbedUnimplementedServerRpcServer() {}

// UnsafeServerRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerRpcServer will
// result in compilation errors.
type UnsafeServerRpcServer interface {
	mustEmbedUnimplementedServerRpcServer()
}

func RegisterServerRpcServer(s grpc.ServiceRegistrar, srv ServerRpcServer) {
	s.RegisterService(&ServerRpc_ServiceDesc, srv)
}

func _ServerRpc_CreatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerRpcServer).CreatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerRpc_CreatePerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerRpcServer).CreatePerson(ctx, req.(*CreatePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerRpc_ServiceDesc is the grpc.ServiceDesc for ServerRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ServerRpc",
	HandlerType: (*ServerRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePerson",
			Handler:    _ServerRpc_CreatePerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
